// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUQgYX-rDRfRruhW_nqxPnrgRGnS_b0IA',
    appId: '1:73723741693:web:d7179e187f015b1df50594',
    messagingSenderId: '73723741693',
    projectId: 'cartzy-8004b',
    authDomain: 'cartzy-8004b.firebaseapp.com',
    storageBucket: 'cartzy-8004b.firebasestorage.app',
    measurementId: 'G-Q107H7H23W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjJidyzZfjFpu9r6BuwWfqerNv7fYlxL0',
    appId: '1:73723741693:android:ad9730ab1ac31228f50594',
    messagingSenderId: '73723741693',
    projectId: 'cartzy-8004b',
    storageBucket: 'cartzy-8004b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZyoJBjaDJe20QRY5DlQ_JjacRjgWmHss',
    appId: '1:73723741693:ios:81e6a1185a9bf2b5f50594',
    messagingSenderId: '73723741693',
    projectId: 'cartzy-8004b',
    storageBucket: 'cartzy-8004b.firebasestorage.app',
    iosBundleId: 'com.example.cartze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZyoJBjaDJe20QRY5DlQ_JjacRjgWmHss',
    appId: '1:73723741693:ios:81e6a1185a9bf2b5f50594',
    messagingSenderId: '73723741693',
    projectId: 'cartzy-8004b',
    storageBucket: 'cartzy-8004b.firebasestorage.app',
    iosBundleId: 'com.example.cartze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUQgYX-rDRfRruhW_nqxPnrgRGnS_b0IA',
    appId: '1:73723741693:web:4385375cc51a968cf50594',
    messagingSenderId: '73723741693',
    projectId: 'cartzy-8004b',
    authDomain: 'cartzy-8004b.firebaseapp.com',
    storageBucket: 'cartzy-8004b.firebasestorage.app',
    measurementId: 'G-SQ6ZHTL0DZ',
  );
}
